# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_1
  pid: {p: 105.0, i: 10.0, d: 0.1}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_2
  pid: {p: 103.0, i: 6.0, d: 0.1}
joint3_position_controller:
 type: effort_controllers/JointPositionController
 joint: joint_3
 pid: {p: 105.0,i: 6.0,d: 0.1}
joint4_position_controller:
 type: effort_controllers/JointPositionController
 joint: joint_4
 pid: {p: 105.0,i: 6.0,d: 0.1}
joint51_position_controller:
 type: effort_controllers/JointPositionController
 joint: joint_51
 pid: {p: 105.0,i: 6.0,d: 0.1}
joint52_position_controller:
 type: effort_controllers/JointPositionController
 joint: joint_52
 pid: {p: 105.0,i: 6.0,d: 0.1}